version: '3'
services:
  drupal:
    build: drupal_nginxAlpine
    depends_on:
      - db
    links:
      - db       
    ports:
            - '80:8080'

    volumes:
            - storage-drupal:/var/www/drupal/modules
            - storage-drupal:/var/www/drupal/profiles
            - storage-drupal:/var/www/drupal/themes
            - storage-drupal:/var/www/drupal/sites
    networks:
      - drupal-net
    restart: always

  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_DATABASE: drupal
      # So you don't have to use root, but you can if you like
      MYSQL_USER: drupal
      # You can use whatever password you like
      MYSQL_PASSWORD: drupal
      # Password for root access
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - storage-mysql:/var/lib/mysql
    networks:
      - drupal-net
    restart: always

networks:
  drupal-net:


volumes:
  storage-drupal:
  storage-mysql:

